### ISSUE TITLE
Locations Created Within a Branch Are Not Available to Be Assigned to Devices

### ISSUE THREAD

**Issue by adparis99** [netboxlabs/netbox-branching#119]
### Plugin Version

0.4.0

### NetBox Version

4.1.0

### Python Version

3.10

### Steps to Reproduce

1. Create a branch
2. Activate that branch
3. Create a location that is assigned to a pre-existing site
4. Create a new device
5. Assign the device to the pre-existing site
6. Attempt to assign the device to the newly created location

### Expected Behavior

The newly created location is available for selection.

### Observed Behavior

The newly created location is not available for selection.

**Comment by jeremystretch** [comment]
The issue here is that, although the API request is authenticated and the branch is active for the request, the middleware currently only recognizes a separate HTTP header specifying the branch for API requests. We need to tweak it so that the authenticated session is also inspected to determine the branch.
