### ISSUE TITLE
Excluded Models create ObjectChange records in the branch

### ISSUE THREAD

**Issue by arthanson** [netboxlabs/netbox-branching#163]
### Plugin Version

v0.5.1

### NetBox Version

v4.1.5

### Python Version

3.11.9

### Steps to Reproduce

1. Make a new branch
2. Switch to the branch
3. Create a custom field (can do it on circuits, doesn't matter params)
4. merge the branch
5. refresh when merged and see error
6. branch won’t merge as it’s trying to create the custom field in main which already exists.

### Expected Behavior

branch is merged and ObjectChange records for custom fields should be created in main branch as they are in excluded models.

### Observed Behavior

ObjectChange is created in new branch, not main.  When merging it will get an error of duplicate records.

**Comment by jeremystretch** [comment]
The immediate cause of this bug is the removal of [a piece of logic](https://github.com/netboxlabs/netbox-branching/commit/49267c39b536d34e5875a209736847d6a56a1d3b#diff-ee014fe44029f805492b0ab995ebd34236faa77936956b130d0d1cfb71aeb43a) from `BranchAwareRouter` to fix #98. While restoring this code resolves this specific bug, we still need to address the cable path issue captured in #98 via some other means to be identified.

This bug also exposes something of a weakness in the database router logic. The purpose of the custom database router is to direct the use of a branch-aware connection for models which support branching, and otherwise use the default behavior (by not specifying a connection). This is the relevant code:

```python
        # Bail if the model does not support branching
        app_label, model_name = model._meta.label.lower().split('.')
        if model_name not in registry['model_features']['branching'].get(app_label, []):
            return

        # Return the schema for the active branch (if any)
        if branch := active_branch.get():
            return f'schema_{branch.schema_name}'
```

The CustomField model does not support branching, so when a custom field is created, the database router returns null, and the default connection is used. Likewise, the ObjectChange record resulting from the custom field's creation also uses the default connection, because the ObjectChange model also does not support branching.

Interestingly though, when creating an instance of a model which _does_ support branching, the resulting ObjectChange record uses the branch connection (rather than the default). I suspect this is due to Django's use of [hints](https://docs.djangoproject.com/en/5.1/topics/db/multi-db/#hints) for inferring the appropriate connection but this needs more investigation.

A solution for handling cable paths still needs to be devised, as that particular model falls into a gray area: CablePath does not support change logging (as it exists solely to record end-to-end cable traces effected by the creation of cables and other models), but its table must be replicated on branches to ensure cable tracing functions correctly.
